name: flutter_trial
description: A first attempt to use flutter to record audio on Windows Desktop.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  styled_widget: 0.4.0+3
  font_awesome_flutter: 9.2.0
  fluent_ui: 3.9.0
  system_theme: 1.0.1
  path_provider: 2.0.9
  flutter_modular: 1.0.0
  mobx: 2.0.6+1
  flutter_mobx: 2.0.4
  ffi: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: 2.1.7
  mobx_codegen: 2.0.5+2
  flutter_lints: ^1.0.0
  ffigen: 4.1.3
  intl: ^0.17.0

ffigen:
  output: 'lib/pages/native_audio_recording.dart'
  name: 'NativeAudioRecording'
  description: 'Native Audio Recording using SDL'
  headers:
    entry-points:
      - 'windows/native_lib/native_sdl.h'

flutter:
  uses-material-design: true
  generate: true
