// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
import 'dart:ffi' as ffi;

/// Native Audio Recording using SDL
class NativeAudioRecording {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  NativeAudioRecording(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  NativeAudioRecording.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void init(
    ffi.Pointer<ffi.Int8> wavFile,
  ) {
    return _init(
      wavFile,
    );
  }

  late final _initPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<ffi.Int8>)>>(
          'init');
  late final _init =
      _initPtr.asFunction<void Function(ffi.Pointer<ffi.Int8>)>();

  void start() {
    return _start();
  }

  late final _startPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('start');
  late final _start = _startPtr.asFunction<void Function()>();

  void stop() {
    return _stop();
  }

  late final _stopPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>('stop');
  late final _stop = _stopPtr.asFunction<void Function()>();
}
